version: '3.9'
services:
  monitoring:
    build: .
    environment:
      DB_HOST: "db"
      DB_PORT: "5432"
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      BACKUP_FOLDER: "/home/hovoh/backups"
    env_file: ./.env
    volumes:
      - "./db_backups:/home/hovoh/backups"
    depends_on:
      - db
