export const ONLY_VAULT_OWNER = "Vault is not owned by caller";
export const BELOW_MINIMUM_COLLATERAL_PERCENTAGE = "Borrow would put vault below minimum collateral percentage";
export const NOT_ENOUGH_COLLATERAL = "Account does not have enough collateral";
export const VAULT_NOT_EXIST = "Account does not exist";
export const NOT_BELOW_MINIMUM_COLLATERAL_PERCENTAGE = "Vault is not below minimum collateral percentage"
export const WITHDRAW_HR_BELOW_ONE = "Withdrawal would put health ratio below 1"
export const BORROW_HR_BELOW_ONE = "borrow: Health ratio below 100"
export const LIQUIDATION_TOO_MUCH = "too much collateral is liquidated"
export const LIQUIDATION_CANNOT_LEAVE_SMALL_DEBT = "Cannot leave a small amount of debt";
export const LIQUIDATION_LIQUIDATE_ENTIRE_SMALL_ACCOUNT = "Small accounts have to be liquidated entirely";
export const CALLER_IS_NOT_ADMINISTRATOR = "Caller is not an administrator";
export const MARKET_IS_PAUSED = "Pausable: paused";
export const PRINCIPAL_AMOUNT_TOO_SMALL = "Outstanding principal amount is too small.";
export const NOT_ENOUGH_DAILY_ISSUANCE_LEFT = "Not enough daily issuance left for this borrow amount";