version: "3.9"
services:
  adminer:
    image: adminer
    restart: ${RESTART_POLICY}
    ports:
      - "${ADMINER_PORT}:8080"
  db:
    image: timescale/timescaledb-ha:pg14-latest
    restart: ${RESTART_POLICY}
    ports:
      - "${DB_PORT}:5432"
    environment:
      DB_HOST: "db"
      DB_PORT: "5432"
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db-data:/home/postgres/pgdata/data
      - "/home/hovoh/containers/mclb-monitoring/backups:/home/hovoh/backups"
  grafana:
    image: grafana/grafana-oss
    restart: ${RESTART_POLICY}
    environment:
      MONITOR_URL: "db:5432"
      MONITOR_DB_USER: ${DB_USER}
      MONITOR_DB_NAME: ${DB_NAME}
      MONITOR_DB_PASSWORD: ${DB_PASSWORD}
      GF_AUTH_DISABLE_LOGIN_FORM: "true"
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
    ports:
      - "${GRAF_PORT}:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - /home/hovoh/containers/mclb-monitoring/grafana/dashboards:/var/lib/grafana/dashboards
      - /home/hovoh/containers/mclb-monitoring/grafana/provisioning:/etc/grafana/provisioning
      - /home/hovoh/containers/mclb-monitoring/grafana/grafana.ini:/etc/grafana/grafana.ini
  monitoring:
    image: ghcr.io/millenniumclub3/monitoring:${MONITORING_TAG}
    restart: ${RESTART_POLICY}
    environment:
      DB_HOST: "db"
      DB_PORT: "5432"
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      BACKUP_FOLDER: "/home/hovoh/backups"
      DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN}
      DISCORD_NOTIFICATION_CHANNEL: ${DISCORD_NOTIFICATION_CHANNEL}
      INFURA_KEY: ${INFURA_KEY}
      SIGNER_PRIVATE_KEY: ${SIGNER_PRIVATE_KEY}
      IGNORED_NETWORKS: "31337"
    volumes:
      - "/home/hovoh/containers/mclb-monitoring/backups:/home/hovoh/backups"
    depends_on:
      - db

volumes:
  grafana-data:
  db-data:
